"""
Nested Stage-1 leakage spot-check (Rob concern #2a): retrain Stage 1 with ten
countries' HOST rows excluded, and rebuild their shadows from a model that has
never seen them.

The published LOCO is Stage-2-only: when a country is held out, its shadow was
generated by a classifier trained on its onset dyads (mitigated but not removed
by nb06's OOF overwrite -- non-onset years use the full model, and training-set
membership itself indexes onset).  This spot-check quantifies what remains:

  EXCL = 5 training hosts (Iraq 645, Philippines 840, Sri Lanka 780, Angola 540,
         Nicaragua 093; ~15% of training rows) + 5 never-onset countries
         (UK 200, Japan 740, Canada 020, Zambia 551, Tanzania 510).

Implementation: a thin wrapper over scripts/ablate_stage1.py's nb05-verbatim
training under the CANONICAL spec (iso_chain: 10 baseline lags + contiguity
chain; XW = 109 features -- NOT the archived 20-lag full set), same seed
schedule, with one change: dyads whose HOST is in EXCL leave the training set
(and hence the training-time FP).  Countries still appear on the B-side (as
potential interveners) -- the leak under test is host-side membership.  Then
nb06's universal Nash FP + aggregation runs with the nested model via
fp_rerun.run; its OOF overwrite applies only to non-excluded onset rows, so
excluded countries' rows keep nested-model predictions, clean by construction.

Evaluation: scripts/nested_spotcheck_eval.py (after all draws).

ADDITIVE: writes only data/interim/nested/.
Usage:  .venv/bin/python scripts/nested_spotcheck.py <cy> <ud>     (~2-3 h per draw)
"""
import os
for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS",
           "VECLIB_MAXIMUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_v, "4")

import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import fp_rerun  # noqa: E402  (nb06-verbatim universal FP + aggregation)
from ablate_stage1 import (  # noqa: E402  (nb05-verbatim training, spat_set threaded)
    SPECS, spat_set_for, add_temporal_features, train_super_learner,
    _build_W_cache, update_spatial_lags_proba, MAX_FP_ITER, FP_TOL, SEED, INTERIM)

NESTED = INTERIM / "nested"; NESTED.mkdir(exist_ok=True)
CANON_SPEC = "iso_chain"                      # the promoted canonical W-spec

EXCL = ["645", "840", "780", "540", "093",    # training hosts w/ onsets
        "200", "740", "020", "551", "510"]    # never-onset controls


def main(cy, ud):
    sfx = f"nested_{cy}_{ud}"
    model_path = NESTED / f"sl_model_{sfx}.pkl"
    if not os.environ.get("FORCE") and (NESTED / f"cy_shadow_{sfx}.parquet").exists():
        print(f"skip {sfx} (cached)", flush=True)
        return
    spat_set = spat_set_for(SPECS[CANON_SPEC])
    dd = add_temporal_features(pd.read_parquet(INTERIM / f"dd_spat_{cy}_{ud}.parquet"))
    full_mask = (dd["onset_A"] == 1) & dd["intervention"].notna()
    keep = ~dd["ccode_A"].isin(EXCL)
    train = dd[full_mask & keep].copy()
    y = train["intervention"].astype(int).values
    W_cache = _build_W_cache(dd, dd["onset_A"] == 1)   # canonical form; B-side intact
    print(f"── nested {cy}_{ud}: n={len(train):,} training dyads "
          f"({int((full_mask & ~keep).sum()):,} excluded), "
          f"{(y == 1).sum()} gov, {(y == 2).sum()} opp", flush=True)

    prev_spat = None
    result = None
    for fp_iter in range(MAX_FP_ITER):
        result = train_super_learner(train, y, spat_set, seed=SEED + cy * 10 + ud)
        p_gov, p_opp = result["oof_proba"][:, 1], result["oof_proba"][:, 2]
        train_updated = update_spatial_lags_proba(train, p_gov, p_opp, W_cache=W_cache)
        new_spat = train_updated[["spat_gov", "spat_opp"]].fillna(0).values
        if prev_spat is not None and float(np.abs(new_spat - prev_spat).mean()) < FP_TOL:
            break
        prev_spat = new_spat
        train = train_updated

    oof_df = train[["ddyear", "ccode_A", "ccode_B", "year", "intervention"]].copy()
    oof_df["p_none"] = result["oof_proba"][:, 0]
    oof_df["p_gov"] = result["oof_proba"][:, 1]
    oof_df["p_opp"] = result["oof_proba"][:, 2]
    oof_df["cy"], oof_df["ud"], oof_df["spec"] = cy, ud, f"{CANON_SPEC}+excl10"
    oof_path = NESTED / f"sl_oof_{sfx}.parquet"
    oof_df.to_parquet(oof_path, index=False)
    joblib.dump(result, model_path)

    slr = result["component_metrics"].query("method == 'super_learner'").iloc[0]
    print(f"trained {sfx} [{fp_iter + 1} fp]: PRL={slr['prl']:.4f} AUC={slr['auc']:.4f}; "
          f"universal FP next", flush=True)

    fp_rerun.run(cy, ud, model_path=model_path, oof_path=oof_path,
                 out_dir=NESTED, tag="nested")


if __name__ == "__main__":
    main(int(sys.argv[1]), int(sys.argv[2]))
